import { useEffect, useState } from "react";
import { downloadExpenseReportApi, getExpenseReportApi, getExpenseSettingsApi, saveExpenseSettingsApi } from "../../api/expenseReportApi";
import { downloadResponse } from "../../utils/download";
import { getStoredUser, hasPermission } from "../../utils/permissions";
import "./Operations.css";
const FIELDS=[["rate_per_ton","Rate per 1 ton production"],["staff_salary","Staff salary"],["hardware_expense","Hardware expense per day"],["maintenance_expense","Maintenance expense per day"],["zinc_spray_expense","Zinc spray expense per day"],["electricity_per_day","Electricity bill per day"],["gas_bottle_rate","Gas bottle rate"],["chemicals_per_day","Chemicals expense per day"],["ms_wire_per_day","MS wire expense per day"],["rent_expense","Rent expense per day"],["acid_expense","Acid expense per day"],["crane_expense","Crane expense per day"],["other_expense","Other expense per day"]];
const EXPENSES=[["salary_per_day","Salary per day"],["hardware_per_day","Hardware expense per day"],["maintenance_per_day","Maintenance per day"],["zinc_spray_per_day","Zinc spray per day"],["electricity_per_day","Electricity bill per day"],["gas_per_day","Gas expense per day"],["chemicals_per_day","Chemicals per day"],["ms_wire_per_day","MS wire per day"],["rent_expense","Rent expense"],["acid_expense","Acid expense"],["crane_expense","Crane expense"],["other_expense","Other expense"]];
const month=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`};const money=v=>Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});const num=v=>Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:3});
export default function ExpenseReportScreen(){const user=getStoredUser(),canSettings=hasPermission(user,"expense_report.settings"),canReport=hasPermission(user,"expense_report.report");const [mode,setMode]=useState("report"),[report,setReport]=useState(null),[form,setForm]=useState(Object.fromEntries(FIELDS.map(([k])=>[k,"0"]))),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{setLoading(true);setError("");try{if(mode==="settings"){const r=await getExpenseSettingsApi();setForm(Object.fromEntries(FIELDS.map(([k])=>[k,String(r.data?.[k]??0)])))}else setReport((await getExpenseReportApi({month:month()})).data)}catch(e){setError(e.response?.data?.message||"Could not load expense data.")}finally{setLoading(false)}};useEffect(()=>{load()},[mode]);
 const save=async()=>{if(FIELDS.some(([k])=>!/^[0-9]+(?:\.[0-9]{1,2})?$/.test(form[k])))return setError("Enter every expense as a positive amount or zero with up to two decimals.");setSaving(true);try{const r=await saveExpenseSettingsApi(Object.fromEntries(FIELDS.map(([k])=>[k,Number(form[k])])));setSuccess(r.message||"Expense settings saved.");setMode("report")}catch(e){setError(e.response?.data?.message||"Could not save settings.")}finally{setSaving(false)}};
 const pdf=async()=>{try{downloadResponse(await downloadExpenseReportApi({month:month()}),`expense-report-${month()}.pdf`)}catch(e){setError(e.response?.data?.message||"Could not generate PDF.")}};const t=report?.totals||{};
 return <section className="ops-page"><header className="ops-header"><div><h2>{mode==="settings"?"Expense Settings":"Expense Report"}</h2><p className="ops-muted">{mode==="report"?new Date(`${month()}-01`).toLocaleDateString("en-IN",{month:"long",year:"numeric"}):"Rates used for the monthly plant cost calculation"}</p></div><div className="ops-actions">{canSettings&&<button className="ops-button secondary" onClick={()=>setMode(mode==="report"?"settings":"report")}>{mode==="report"?"Settings":"Back to report"}</button>}{mode==="report"&&canReport&&<button className="ops-button" onClick={pdf}>Generate PDF</button>}</div></header>{error&&<div className="ops-error">{error}</div>}{success&&<div className="ops-success">{success}</div>}{loading?<div className="ops-card">Loading…</div>:mode==="settings"?<><div className="ops-card"><div className="ops-form">{FIELDS.map(([k,l])=><label className="ops-field" key={k}>{l}<input type="number" min="0" step="0.01" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div></div><button className="ops-button" disabled={saving} onClick={save}>{saving?"Saving…":"Save expense settings"}</button></>:report&&<><div className="ops-hero"><small>RUNNING PLANT COST</small><strong>₹{money(t.running_plant_cost)}</strong><span>per kg · based on average daily production</span></div><div className="ops-grid">{[["Total daily expense",`₹${money(t.total_expense)}`],["Plant zinc stock",`${num(t.plant_zinc_stock_kg)} kg`],["Purchased zinc this month",`${num(t.purchased_zinc_kg)} kg`],["Monthly MS production",`${num(t.total_ms_production_kg/1000)} ton`],["Average production/day",`${num(t.average_ms_production_per_day_kg/1000)} ton`],["Average zinc consumption",`${num(t.average_zinc_consumption_percent)}%`]].map(([a,b])=><div className="ops-metric" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="ops-card"><h3>All expenses</h3>{EXPENSES.map(([k,l])=><div className="ops-list-row" key={k}><span>{l}</span><b>₹{money(report.expenses?.[k])}</b></div>)}<div className="ops-list-row"><strong>Total expense</strong><strong>₹{money(t.total_expense)}</strong></div></div></>}</section>}
