import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import { createContractorApi, deleteContractorApi, getContractorDirectoryApi, updateContractorApi } from "../../api/contractorApi";
import { createFinancialYearApi, deleteFinancialYearApi, getFinancialYearsApi, setCurrentFinancialYearApi, updateFinancialYearApi } from "../../api/financialYearsApi";
import { createItemApi, deleteItemApi, getItemsApi, updateItemApi } from "../../api/itemsApi";
import "./Operations.css";

const configs={items:{title:"Items",placeholder:"Item name",get:getItemsApi,create:createItemApi,update:(id,value)=>updateItemApi({id,itemName:value}),remove:deleteItemApi,value:x=>x.item_name},contractors:{title:"Contractors",placeholder:"Contractor name",get:getContractorDirectoryApi,create:createContractorApi,update:(id,value)=>updateContractorApi({id,name:value}),remove:deleteContractorApi,value:x=>x.name}};
function Directory({type}){const c=configs[type],[rows,setRows]=useState([]),[value,setValue]=useState(""),[editing,setEditing]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=()=>c.get().then(r=>setRows(Array.isArray(r.data)?r.data:[])).catch(e=>setError(e.response?.data?.message||`Could not load ${c.title.toLowerCase()}.`));useEffect(()=>{load();},[type]);const save=async()=>{const clean=value.trim().replace(/\s+/g," ");if(!clean)return setError(`Enter a ${c.placeholder.toLowerCase()}.`);setBusy(true);try{editing?await c.update(editing.id,clean):await c.create(clean);setEditing(null);setValue("");await load()}catch(e){setError(e.response?.data?.message||"Could not save.")}finally{setBusy(false)}};const remove=async x=>{if(!confirm(`Delete “${c.value(x)}”?`))return;try{await c.remove(x.id);await load()}catch(e){setError(e.response?.data?.message||"Could not delete.")}};return <><div className="ops-card"><h3>{editing?`Edit ${c.title.slice(0,-1)}`:`Add ${c.title.slice(0,-1)}`}</h3><div className="ops-actions"><input placeholder={c.placeholder} value={value} maxLength="120" onChange={e=>setValue(e.target.value)}/>{editing&&<button className="ops-button secondary" onClick={()=>{setEditing(null);setValue("")}}>Cancel</button>}<button className="ops-button" disabled={busy} onClick={save}>Save</button></div></div>{error&&<div className="ops-error">{error}</div>}<div className="ops-card"><h3>All {c.title.toLowerCase()}</h3>{rows.map(x=><div className="crud-row" key={x.id}><b>{c.value(x)}</b><div className="ops-actions"><button className="ops-button secondary" onClick={()=>{setEditing(x);setValue(c.value(x))}}>Edit</button><button className="ops-button danger" onClick={()=>remove(x)}>Delete</button></div></div>)}{!rows.length&&<div className="ops-empty">No records added.</div>}</div></>}
function FinancialYears(){const [rows,setRows]=useState([]),[value,setValue]=useState(""),[editing,setEditing]=useState(null),[error,setError]=useState("");const load=()=>getFinancialYearsApi().then(r=>setRows(Array.isArray(r.data)?r.data:[])).catch(e=>setError(e.response?.data?.message||"Could not load financial years."));useEffect(()=>{load();},[]);const save=async()=>{if(!/^\d{4}-\d{2}$/.test(value))return setError("Use financial year format YYYY-YY, for example 2026-27.");try{editing?await updateFinancialYearApi({id:editing.id,financialYear:value}):await createFinancialYearApi(value);setEditing(null);setValue("");await load()}catch(e){setError(e.response?.data?.message||"Could not save financial year.")}};const remove=async x=>{if(!confirm(`Delete financial year ${x.financial_year}?`))return;try{await deleteFinancialYearApi(x.id);await load()}catch(e){setError(e.response?.data?.message||"Could not delete financial year.")}};return <><div className="ops-card"><h3>{editing?"Edit":"Add"} financial year</h3><div className="ops-actions"><input placeholder="2026-27" value={value} onChange={e=>setValue(e.target.value)}/>{editing&&<button className="ops-button secondary" onClick={()=>{setEditing(null);setValue("")}}>Cancel</button>}<button className="ops-button" onClick={save}>Save</button></div></div>{error&&<div className="ops-error">{error}</div>}<div className="ops-card"><h3>Financial years</h3>{rows.map(x=><div className="crud-row" key={x.id}><span><b>{x.financial_year}</b>{x.is_current&&<small className="ops-success" style={{marginLeft:10,padding:4}}>Current</small>}</span><div className="ops-actions">{!x.is_current&&<button className="ops-button" onClick={async()=>{await setCurrentFinancialYearApi(x.id);load()}}>Make current</button>}<button className="ops-button secondary" onClick={()=>{setEditing(x);setValue(x.financial_year)}}>Edit</button><button className="ops-button danger" onClick={()=>remove(x)}>Delete</button></div></div>)}</div></>}
export default function SettingsScreen({initialTab="items"}){const navigate=useNavigate();return <section className="ops-page"><header><h2>{initialTab==="years"?"Financial Years":initialTab==="contractors"?"Contractors":"Items"}</h2><p className="ops-muted">Manage production master records and reporting periods.</p></header><div className="ops-tabs"><button className="ops-tab active" onClick={()=>navigate("/settings")}>Back to Settings</button></div>{initialTab==="years"?<FinancialYears/>:<Directory type={initialTab}/>}</section>}
